services:
  backend:
    build: 
      context: ./apps/backend
    ports:
      - "8000:8000"
    env_file:
      - ./apps/backend/.env
    volumes:
      - ./apps/backend:/app
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=8000

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true
    depends_on:
      - backend